/*
 * ACRONET Project
 * http://www.acronet.cc
 *
 * Copyright ( C ) 2014 Acrotec srl
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms
 * of the EUPL v.1.1 license.  See http://ec.europa.eu/idabc/eupl.html for details.
 */ 


#define ISTANCE_NUM BOOST_PP_FRAME_ITERATION(2)

#define MODULE_ISTANCE_CHAN BOOST_PP_SEQ_ELEM(ISTANCE_NUM,MODULE_ISTANCES)
#define METHOD_NAME_ISTANCE_TRAIL BOOST_PP_CAT(_ist_,ISTANCE_NUM)


#define MODULE_FLASH_DATA_TUPLE BOOST_PP_SEQ_ELEM(ISTANCE_NUM,T026_PER_ISTANCE_CMD)
#define MODULE_MODBUS_ADDRESS BOOST_PP_TUPLE_ELEM(0,MODULE_FLASH_DATA_TUPLE)


#ifdef MODULE_INTERFACE_INIT
#define MODULE_METHOD_NAME BOOST_PP_CAT(MODULE_INTERFACE_INIT,METHOD_NAME_ISTANCE_TRAIL)
RET_ERROR_CODE MODULE_METHOD_NAME(void)
{
	DEBUG_PRINT_FUNCTION_NAME(NORMAL,"PANEL INIT ON CHAN "BOOST_PP_STRINGIZE(MODULE_ISTANCE_CHAN) );

	return MODULE_INTERFACE_INIT(&(MODULE_PRIVATE_DATA));
}
#endif

#ifdef MODULE_INTERFACE_RESET
#define MODULE_METHOD_NAME BOOST_PP_CAT(MODULE_INTERFACE_RESET,METHOD_NAME_ISTANCE_TRAIL)
RET_ERROR_CODE MODULE_METHOD_NAME(void)
{
	return AC_ERROR_OK;
}
#undef MODULE_METHOD_NAME
#endif


#ifdef MODULE_INTERFACE_GETDATA
#define MODULE_METHOD_NAME BOOST_PP_CAT(MODULE_INTERFACE_GETDATA,METHOD_NAME_ISTANCE_TRAIL)
RET_ERROR_CODE  MODULE_METHOD_NAME(MODULE_PUBLIC_DATATYPE * const pData)
{
	return MODULE_INTERFACE_GETDATA(&(MODULE_PRIVATE_DATA),pData);
}
#undef MODULE_METHOD_NAME
#endif
