/*
 * ACRONET Project
 * http://www.acronet.cc
 *
 * Copyright ( C ) 2014 Acrotec srl
 * All rights reserved.
 *
 * This software may be modified and distributed under the terms
 * of the EUPL v.1.1 license.  See http://ec.europa.eu/idabc/eupl.html for details.
 */


/*
#define DECLARATION_ITER2 BOOST_PP_SEQ_ELEM(BOOST_PP_ITERATION(),MODULE_DECLARATION)
*/

#define METHOD_NAME_ISTANCE_TRAIL BOOST_PP_CAT(_ist_,BOOST_PP_ITERATION())
#define METHOD_FUNCTION_DECLARE(MNAME) BOOST_PP_CAT(MNAME,METHOD_NAME_ISTANCE_TRAIL)


#ifdef MODULE_INTERFACE_INIT
RET_ERROR_CODE METHOD_FUNCTION_DECLARE(MODULE_INTERFACE_INIT)(void);
#endif

#ifdef MODULE_INTERFACE_ENABLE
void METHOD_FUNCTION_DECLARE(MODULE_INTERFACE_ENABLE)(void);
#endif

#ifdef MODULE_INTERFACE_DISABLE
void METHOD_FUNCTION_DECLARE(MODULE_INTERFACE_DISABLE)(void);
#endif

#ifdef MODULE_INTERFACE_YIELD
bool METHOD_FUNCTION_DECLARE(MODULE_INTERFACE_YIELD)(void);
#endif

#ifdef MODULE_INTERFACE_RESET
RET_ERROR_CODE METHOD_FUNCTION_DECLARE(MODULE_INTERFACE_RESET)(void);
#endif

#ifdef MODULE_INTERFACE_GETDATA
RET_ERROR_CODE METHOD_FUNCTION_DECLARE(MODULE_INTERFACE_GETDATA)(MODULE_PUBLIC_DATATYPE * const);
#endif
/*
#ifdef MODULE_INTERFACE_DATA2STRING
RET_ERROR_CODE METHOD_FUNCTION_DECLARE(MODULE_INTERFACE_DATA2STRING)(const MODULE_PUBLIC_DATATYPE * const, char * const, uint16_t * const);
#endif

#ifdef MODULE_INTERFACE_DATA2STRING_RMAP
RET_ERROR_CODE METHOD_FUNCTION_DECLARE(MODULE_INTERFACE_DATA2STRING_RMAP)( uint8_t * const, const MODULE_PUBLIC_DATATYPE * const, const uint32_t, const uint16_t, char * const, int16_t * const,char * const,int16_t * const);
#endif
*/

#ifdef MODULE_INTERFACE_PERIODIC
void METHOD_FUNCTION_DECLARE(MODULE_INTERFACE_PERIODIC)(void);
#endif

#undef METHOD_NAME_ISTANCE_TRAIL 
#undef METHOD_FUNCTION_DECLARE
